language: python
sudo: false
dist: trusty

python:
  - "3.6"
  - "2.7"
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - libopenblas-dev
      - liblapack-dev
install:
  - "pip install -r requirements.txt"
  - "travis_retry python setup.py develop"
script:
  python -m pytest
